feature(zj): add level6 and deepseek api
opendilab/LLMRiddles pull request #26
Opened 2024-07-24 06:02 UTC by Sylvia-jing

新增了 deepseek 的API和level 6的关卡

2024-07-24 13:01 UTC, TuTuHuss requested changes

2024-07-28 06:28 UTC, TuTuHuss requested changes

2024-07-28 06:28 UTC, TuTuHuss commented on app.py
> +                "点击“提示”即可获得提示。"  # 更新提示信息
don‘t return tips here,  try to make tips module become a TextArea

2024-07-30 06:06 UTC, PaParaZz1 approved these changes

2024-07-30 09:22 UTC, merged